In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\No Proxy\Downloads\Automobile.csv")
df

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [6]:
df.isnull().sum()

symboling              0
normalized_losses      0
make                   0
fuel_type              0
aspiration             0
number_of_doors        0
body_style             0
drive_wheels           0
engine_location        0
wheel_base             0
length                 0
width                  0
height                 0
curb_weight            0
engine_type            0
number_of_cylinders    0
engine_size            0
fuel_system            0
bore                   0
stroke                 0
compression_ratio      0
horsepower             0
peak_rpm               0
city_mpg               0
highway_mpg            0
price                  0
dtype: int64

In [7]:
df.describe()

,symboling,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
count,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000
mean,0.840796,125.189055,98.797015,174.200995,65.889055,53.766667,2555.666667,126.875622,3.329701,3.261741,10.164279,103.263682,5121.393035,25.179104,30.686567,13207.129353
std,1.254802,33.572966,6.066366,12.322175,2.101471,2.447822,517.296727,41.546834,0.268166,0.317875,4.004965,37.389372,479.624905,6.423220,6.815150,7947.066342
min,-2.000000,65.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,0.000000,101.000000,94.500000,166.800000,64.100000,52.000000,2169.000000,98.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7775.000000
50%,1.000000,122.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,2.000000,150.000000,102.400000,183.500000,66.600000,55.500000,2926.000000,141.000000,3.580000,3.460000,9.400000,116.000000,5500.000000,30.000000,34.000000,16500.000000
max,3.000000,256.000000,120.900000,208.100000,72.000000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   symboling            201 non-null    int64
 1   normalized_losses    201 non-null    int64
 2   make                 201 non-null    object
 3   fuel_type            201 non-null    object
 4   aspiration           201 non-null    object
 5   number_of_doors      201 non-null    object
 6   body_style           201 non-null    object
 7   drive_wheels         201 non-null    object
 8   engine_location      201 non-null    object
 9   wheel_base           201 non-null    float64
 10  length               201 non-null    float64
 11  width                201 non-null    float64
 12  height               201 non-null    float64
 13  curb_weight          201 non-null    int64
 14  engine_type          201 non-null    object
 15  number_of_cylinders  201 non-null    object
 16  engine_size          201 non-null    int64
 17  fuel_system          201 non-null    object
 18  bore                 201 non-null    float64
 19  stroke               201 non-null    float64
 20  compression_ratio    201 non-null    float64
 21  horsepower           201 non-null    int64
 22  peak_rpm             201 non-null    int64
 23  city_mpg             201 non-null    int64
 24  highway_mpg          201 non-null    int64
 25  price                201 non-null    int64
dtypes: float64(7), int64(9), object(10)
memory usage: 41.0+ KB

In [11]:
for i in df:
    if df[i].dtype=='object':
        df[i]=df[i].str.lower()

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   symboling            201 non-null    int64
 1   normalized_losses    201 non-null    int64
 2   make                 201 non-null    object
 3   fuel_type            201 non-null    object
 4   aspiration           201 non-null    object
 5   number_of_doors      201 non-null    object
 6   body_style           201 non-null    object
 7   drive_wheels         201 non-null    object
 8   engine_location      201 non-null    object
 9   wheel_base           201 non-null    float64
 10  length               201 non-null    float64
 11  width                201 non-null    float64
 12  height               201 non-null    float64
 13  curb_weight          201 non-null    int64
 14  engine_type          201 non-null    object
 15  number_of_cylinders  201 non-null    object
 16  engine_size          201 non-null    int64
 17  fuel_system          201 non-null    object
 18  bore                 201 non-null    float64
 19  stroke               201 non-null    float64
 20  compression_ratio    201 non-null    float64
 21  horsepower           201 non-null    int64
 22  peak_rpm             201 non-null    int64
 23  city_mpg             201 non-null    int64
 24  highway_mpg          201 non-null    int64
 25  price                201 non-null    int64
dtypes: float64(7), int64(9), object(10)
memory usage: 41.0+ KB

In [17]:
df['number_of_cylinders']=df['number_of_cylinders'].map({'two':2,'three':3,'four':4,'five':5,'six':6,'eight':8,'twelve':12})

In [19]:
df['fuel_system']=df['fuel_system'].map({
    'mpfi': 'Multi-Point Fuel Injection',
    'spdi': 'Single-Point Fuel Injection',
    '2bbl': 'Two-Barrel Carburetor',
    '1bbl': 'One-Barrel Carburetor',
    'idi': 'Indirect Injection',
    'dohc': 'Dual Overhead Cam',
    'ohc': 'Overhead Cam',
    'lpg': 'Liquefied Petroleum Gas',
    'diesel': 'Diesel Engine',
})

In [21]:
df['horsepower']=df['horsepower'].astype(int)

In [22]:
df['peak_rpm']=df['peak_rpm'].astype(int)

In [23]:
df['price']=df['price'].astype(int)

In [24]:
df['hp_KW']=df['horsepower']*0.7457

In [25]:
df['hp_KW']

0       82.7727
1       82.7727
2      114.8378
3       76.0614
4       85.7555
         ...
196     85.0098
197    119.3120
198     99.9238
199     79.0442
200     85.0098
Name: hp_KW, Length: 201, dtype: float64

In [26]:
df['Power_to_weight_ratio']=df['horsepower']/df['curb_weight']

In [27]:
df['Engine_eff']=df['horsepower']/df['engine_size']

In [28]:
df['Fuel_eff']=df['city_mpg']/df['highway_mpg']

In [29]:
import numpy as np

In [30]:
df['categories']=np.where(df['compression_ratio']<9,'low',
                 np.where(df['compression_ratio']<=11,'medium','high'))
df

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,horsepower,peak_rpm,city_mpg,highway_mpg,price,hp_KW,Power_to_weight_ratio,Engine_eff,Fuel_eff,categories
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,111,5000,21,27,13495,82.7727,0.043564,0.853846,0.777778,medium
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,111,5000,21,27,16500,82.7727,0.043564,0.853846,0.777778,medium
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,154,5000,19,26,16500,114.8378,0.054552,1.013158,0.730769,medium
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,102,5500,24,30,13950,76.0614,0.043646,0.935780,0.800000,medium
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,115,5500,18,22,17450,85.7555,0.040722,0.845588,0.818182,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,114,5400,23,28,16845,85.0098,0.038618,0.808511,0.821429,medium
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,160,5300,19,25,19045,119.3120,0.052476,1.134752,0.760000,low
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,134,5500,18,23,21485,99.9238,0.044489,0.774566,0.782609,low
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,106,4800,26,27,22470,79.0442,0.032950,0.731034,0.962963,high
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,114,5400,19,25,22625,85.0098,0.037231,0.808511,0.760000,medium